services:
  publisher:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://root:pass@mongo:27017/
      - DB_NAME=dev
    depends_on:
      - mongo

  subscriber:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./verification:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=J83NDY5QuFpeurg6bK3112pW1laahA
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  mongo-data: