services:
  publisher:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=dev
    depends_on:
      - rabbitmq

  subscriber:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./verification:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=J83NDY5QuFpeurg6bK3112pW1laahA
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
